### ISSUE TITLE
Add Contributions and Settings tables in an specific position in the README

### ISSUE THREAD

**Issue by AllanOricil** [usernamehw/vscode-contributions#12]
I have a README and when I ran the command to generate the contribution commands and settings it appended the values to the end of my README. But what I really wanted is to add those generated tables to a place that I have specified in the README. You can use a comment as a placeholder. Example:

````REAME

LOTS OS COOL README TEXT

....

<!-- CONTRIBUTIONS -->

...

MORE README STUFF

<!-- SETTINGS -->

````

These comments are never rendered but they are there, then you can use their position to determine where to add the generated tables.

**Comment by AllanOricil** [comment]
This is already implemented. Thanks :D

**Comment by usernamehw** [comment]
What happens when you move those comments; does it also append to the end instead of replacing them?

**Comment by AllanOricil** [comment]
Yes, it does exactly it. First it appends the generated text to the end of the file, but it is surrounded by comment tags which you can move to anywhere in your README. To test this feature I moved the two comments to the beginning of my README, then I deleted part of the text, and finally I ran the command again and verified that the text was regenerated in the new position.
