### ISSUE TITLE
Add Dollar Markdown Emoji to the setting item when there is a keyword like 'paid' in the description

### ISSUE THREAD

**Issue by AllanOricil** [usernamehw/vscode-contributions#13]
Add Dollar Icon to setting item when there is a keyword like 'paid' in the description

**Comment by AllanOricil** [comment]
Refer to this https://gist.github.com/rxaviers/7360908

There are many icons there. You can use their names 


💰 :moneybag: 
💴 :yen: 
💵 :dollar:
💷 :pound: 
💶 :euro: 
💳 :credit_card:
💸 :money_with_wings:

**Comment by usernamehw** [comment]
So, as an example:

|Setting|Type|Default|Description|
|-|-|-|-|
|sort|string|"default"|How to sort items in a table.|

===>

|Setting|Type|Default|Description|
|-|-|-|-|
|💲 sort|string|"default"|How to sort items in a table (paid).|

**Comment by AllanOricil** [comment]
Amazing !
![image](https://user-images.githubusercontent.com/55927613/115119189-022c3480-9f9f-11eb-9831-192bb659d119.png)
