### ISSUE TITLE
Setting to move out common prefix from table

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-contributions#2]
Before:

## Settings

|Setting|Type|Default|Description|
|-|-|-|-|
|contributions.sort|string|"default"|How to sort items in a table.|
|contributions.addStartEndDelimiters|boolean|**true**|Add start and end delimiters to the table.|

After:

## Settings (prefix "contributions.")

|Setting|Type|Default|Description|
|-|-|-|-|
|sort|string|"default"|How to sort items in a table.|
|addStartEndDelimiters|boolean|**true**|Add start and end delimiters to the table.|

**Comment by RandomFractals** [comment]
Good call since vs marketplace has super large font on md tables and description got cut off in my snippet viewer docs recently due to long setting names that can't be wrapped.

Maybe instead of adding prefix to Settings section title add a text line that says: XYZ extension settings start with `<extension-id>`, where id from package.json by default, and XYZ is extension display name.

**Comment by usernamehw** [comment]
@RandomFractals what about column title:

---

## Settings

|Setting (prefix "contributions.")|Type|Default|Description|
|-|-|-|-|
|sort|string|"default"|How to sort items in a table.|
|addStartEndDelimiters|boolean|**true**|Add start and end delimiters to the table.|

**Comment by usernamehw** [comment]
No, the table gained too much width.

**Comment by usernamehw** [comment]
It won't work for every extension. For instance Error Lens has `"name"` as `errorlens` but settings use `errorLens`. I'm not sure if vscode has a restriction that `name` must match the settings starting point. So, it probably needs to look for a common prefix to delete it.

**Comment by RandomFractals** [comment]
what if you sample setting names as you parse them, typically they are separated by a dot or a dash. split on those as you load them for the md table, and see what arbitrary common setting prefix ext. dev used.

I know it's a bit more extra work, but I think it can be done with that approach.
