### ISSUE TITLE
Automatically insert it into README

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-contributions#4]
Create a comment of the type:

```markdown
<!-- GENERATED_SETTINGS -->
...
<!-- GENERATED_SETTINGS_END -->

<!-- GENERATED_COMMANDS -->
...
<!-- GENERATED_COMMANDS_END -->
```

and make command automatically replace its content on command execution (instead of opening Untitled file).

**Comment by RandomFractals** [comment]
Since I frequently break those sections into Commands and Settings and add screen pics prior to listing them, I would like to have separate replacement placeholders:

```
<!-- Commands -->

<!-- Settings -->
```

or have start and end comments without the `GENERATED` part, like so:

```
<!-- SETTINGS_START -->
...
<!-- SETTINGS_END -->
...
```
