### ISSUE TITLE
Exclude settings/commands from being generated

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-contributions#5]

**Comment by RandomFractals** [comment]
would I even want to do that if I use this extension?

I mean you already have placeholder comments set for commands and settings in readme.md to insert the generated docs for them in #4. so, if you don't find those regions in docs, you'd just skip those parts.

**Comment by usernamehw** [comment]
Specific commands, for instance in some extensions I have commands only visible when running in dev mode

```js
"commandPalette": [
    {
        "command": "todomd.clearGlobalState",
        "when": "todomd:isDev"
    },
]
```

**Comment by usernamehw** [comment]
And those comments might not work as you expect. When extension won't find `<!-- SETTINGS_START --><!-- SETTINGS_END -->` section => it will insert it at the bottom of the README file.

**Comment by RandomFractals** [comment]
yeah, I am pretty sure we don't want to append to the readme doc if you don't find placeholders for the sections to inject md tables into.
