### ISSUE TITLE
Generate colors

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-contributions#7]

**Comment by RandomFractals** [comment]
is this for theme extensions?

**Comment by usernamehw** [comment]
Nope. For example, Error Lens contributes:

|Name|Light|Dark|
| --- | --- | --- |
|errorLens.errorBackground|`#e4545420`|`#e454541b`|
|errorLens.errorForeground|`#e45454` ![](https://placehold.it/15/e45454?text=+)|`#ff6464`|
|errorLens.errorMessageBackground|`#fff0`|`#fff0`|
|errorLens.warningBackground|`#ff942f20`|`#ff942f1b`|
|errorLens.warningForeground|`#ff942f` ![](https://placehold.it/15/ff942f?text=+)|`#fa973a`|
|errorLens.warningMessageBackground|`#fff0`|`#fff0`|
|errorLens.infoBackground|`#00b7e420`|`#00b7e420`|
|errorLens.infoForeground|`#00b7e4` ![](https://placehold.it/15/00b7e4?text=+)|`#00b7e4`|
|errorLens.infoMessageBackground|`#fff0`|`#fff0`|
|errorLens.hintBackground|`#17a2a220`|`#17a2a220`|
|errorLens.hintForeground|`#2faf64` ![](https://placehold.it/15/2faf64?text=+)|`#2faf64`|
|errorLens.hintMessageBackground|`#fff0`|`#fff0`|
|errorLens.statusBarErrorForeground|`#e45454` ![](https://placehold.it/15/e45454?text=+)|`#ff6464`|
|errorLens.statusBarWarningForeground|`#ff942f` ![](https://placehold.it/15/ff942f?text=+)|`#fa973a`|
|errorLens.statusBarInfoForeground|`#00b7e4` ![](https://placehold.it/15/00b7e4?text=+)|`#00b7e4`|
|errorLens.statusBarHintForeground|`#2faf64` ![](https://placehold.it/15/2faf64?text=+)|`#2faf64`|

https://code.visualstudio.com/api/references/contribution-points#contributes.colors

**Comment by usernamehw** [comment]
This table is missing high contrast column, though.

**Comment by RandomFractals** [comment]
nice!
